"""
This file stores all the sticker file ids of the stickers that the bot is
going to use.
"""


HI_STICKER = "CAACAgQAAxkBAALVtWF9FfZcpK7FbvFqJA_SImU4ZoyMAAJ2BAACRd67BQbx3zHOMN46IQQ"
HERE_STICKER = "CAACAgQAAxkBAALVuWF9FtPW7X9E5uk-MPhGUG8OpmonAAL2AgACRd67BehYLVF3ZoBXIQQ"
CONFUSED_STICKER = "CAACAgQAAxkBAALVvWF9Fv2iP3Yhpao0LQPyb3zJPAxAAAKjAgACRd67BUxb24N2kKxiIQQ"
QUESTION_STICKER = "CAACAgQAAxkBAALVwWF9FwHaORBhKhpTNgMEVdMjk0cfAAKUAgACRd67BdVcb6ElQgnnIQQ"
NOPE_STICKER = "CAACAgQAAxkBAALVxWF9HwRVtjjD6eHYngABFExVnW1idQACZgIAAkXeuwUlb_x9n-QehyEE"
CHARISMATIC_STICKER ="CAACAgQAAxkBAALXV2GIqST8yKC98LlQBpmJMxMDtRQ_AALeAwACRd67BcMfDJAIXp0CIgQ"

